# Generated by the gRPC Python protocol compiler plugin. DO NOT EDIT!
"""Client and server classes corresponding to protobuf-defined services."""
import grpc
import warnings

from . import quiz_service_pb2 as quiz__service__pb2

GRPC_GENERATED_VERSION = '1.78.0'
GRPC_VERSION = grpc.__version__
_version_not_supported = False

try:
    from grpc._utilities import first_version_is_lower
    _version_not_supported = first_version_is_lower(GRPC_VERSION, GRPC_GENERATED_VERSION)
except ImportError:
    _version_not_supported = True

if _version_not_supported:
    raise RuntimeError(
        f'The grpc package installed is at version {GRPC_VERSION},'
        + ' but the generated code in quiz_service_pb2_grpc.py depends on'
        + f' grpcio>={GRPC_GENERATED_VERSION}.'
        + f' Please upgrade your grpc module to grpcio>={GRPC_GENERATED_VERSION}'
        + f' or downgrade your generated code using grpcio-tools<={GRPC_VERSION}.'
    )


class QuizServiceStub(object):
    """Missing associated documentation comment in .proto file."""

    def __init__(self, channel):
        """Constructor.

        Args:
            channel: A grpc.Channel.
        """
        self.GetQuizById = channel.unary_unary(
                '/QuizService/GetQuizById',
                request_serializer=quiz__service__pb2.GetQuizRequest.SerializeToString,
                response_deserializer=quiz__service__pb2.Quiz.FromString,
                _registered_method=True)


class QuizServiceServicer(object):
    """Missing associated documentation comment in .proto file."""

    def GetQuizById(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')


def add_QuizServiceServicer_to_server(servicer, server):
    rpc_method_handlers = {
            'GetQuizById': grpc.unary_unary_rpc_method_handler(
                    servicer.GetQuizById,
                    request_deserializer=quiz__service__pb2.GetQuizRequest.FromString,
                    response_serializer=quiz__service__pb2.Quiz.SerializeToString,
            ),
    }
    generic_handler = grpc.method_handlers_generic_handler(
            'QuizService', rpc_method_handlers)
    server.add_generic_rpc_handlers((generic_handler,))
    server.add_registered_method_handlers('QuizService', rpc_method_handlers)


 # This class is part of an EXPERIMENTAL API.
class QuizService(object):
    """Missing associated documentation comment in .proto file."""

    @staticmethod
    def GetQuizById(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/QuizService/GetQuizById',
            quiz__service__pb2.GetQuizRequest.SerializeToString,
            quiz__service__pb2.Quiz.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)
