# -*- coding: utf-8 -*-
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# NO CHECKED-IN PROTOBUF GENCODE
# source: quiz_service.proto
# Protobuf Python Version: 6.31.1
"""Generated protocol buffer code."""
from google.protobuf import descriptor as _descriptor
from google.protobuf import descriptor_pool as _descriptor_pool
from google.protobuf import runtime_version as _runtime_version
from google.protobuf import symbol_database as _symbol_database
from google.protobuf.internal import builder as _builder
_runtime_version.ValidateProtobufRuntimeVersion(
    _runtime_version.Domain.PUBLIC,
    6,
    31,
    1,
    '',
    'quiz_service.proto'
)
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()




DESCRIPTOR = _descriptor_pool.Default().AddSerializedFile(b'\n\x12quiz_service.proto\"V\n\x08Question\x12\n\n\x02id\x18\x01 \x01(\t\x12\x15\n\rquestion_text\x18\x02 \x01(\t\x12\x0f\n\x07options\x18\x03 \x03(\t\x12\x16\n\x0e\x63orrect_option\x18\x04 \x01(\t\"C\n\x04Quiz\x12\x0e\n\x06quizId\x18\x01 \x01(\t\x12\r\n\x05title\x18\x02 \x01(\t\x12\x1c\n\tquestions\x18\x03 \x03(\x0b\x32\t.Question\" \n\x0eGetQuizRequest\x12\x0e\n\x06quizId\x18\x01 \x01(\t24\n\x0bQuizService\x12%\n\x0bGetQuizById\x12\x0f.GetQuizRequest\x1a\x05.Quizb\x06proto3')

_globals = globals()
_builder.BuildMessageAndEnumDescriptors(DESCRIPTOR, _globals)
_builder.BuildTopDescriptorsAndMessages(DESCRIPTOR, 'quiz_service_pb2', _globals)
if not _descriptor._USE_C_DESCRIPTORS:
  DESCRIPTOR._loaded_options = None
  _globals['_QUESTION']._serialized_start=22
  _globals['_QUESTION']._serialized_end=108
  _globals['_QUIZ']._serialized_start=110
  _globals['_QUIZ']._serialized_end=177
  _globals['_GETQUIZREQUEST']._serialized_start=179
  _globals['_GETQUIZREQUEST']._serialized_end=211
  _globals['_QUIZSERVICE']._serialized_start=213
  _globals['_QUIZSERVICE']._serialized_end=265
# @@protoc_insertion_point(module_scope)
